nome = str(input('Digite seu nome completo: ')).strip()
contagem = nome.split()
print('Seu nome em maiúsculo é: {}'.format(nome.upper()))
print('Seu nome em minúsculo é: {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras!'.format(len(nome)-nome.count(' ')))
print('Seu primeiro nome é {} e ele tem {} letras!'.format(contagem[0], len(contagem[0])))
